apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: octavia
version: 0.1.0
home: https://docs.openstack.org/octavia/latest/
icon: https://www.openstack.org/themes/openstack/images/project-mascots/Octavia/OpenStack_Project_Octavia_vertical.png
sources:
  - https://git.openstack.org/cgit/openstack/octavia
  - https://git.openstack.org/cgit/openstack/openstack-helm
maintainers:
  - name: OpenStack-Helm Authors
