dependencies:
  - name: utils
    repository: file://../../openstack/utils
    version: 0.1.1
  - name: mariadb
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.3
    condition: mariadb.enabled
  - name: rabbitmq
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.1
  - name: memcached
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.2
  - name: region_check
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.0
