global:
  region: regionOne
  domain: evil.corp

ingress:
  tls_client_auth:
    cacrt: |
      -----BEGIN CERTIFICATE-----
      superSecretCertificate
      -----END CERTIFICATE-----

kube-proxy:
  proxy:
    server: https://proxy.evil.corp
  parrot:
    as: 1234
