{{- if .Values.authentication.enabled }}
apiVersion: v1
kind: Secret

metadata:
  name: grafana-ds-certs

data:
  sso.crt: {{ required ".Values.authentication.ssoCert missing" .Values.authentication.ssoCert | b64enc | quote }}
  sso.key: {{ required ".Values.authentication.ssoKey missing" .Values.authentication.ssoKey | b64enc | quote }}
  cacert.crt: {{ required ".Values.authentication.caCert missing" .Values.authentication.caCert | b64enc | quote }}
{{ end }}
