apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-{{.Values.name}}-client
  labels:
    app: mariadb
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: database
data:
  .my.cnf: |
    [client]
    port     = 3306
    socket   = /var/run/mysqld/mysqld.sock
    password = {{ include "mariadb.root_password" . }}
