{{- if .Values.backup_v2.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}-db-backup-v2
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}-db-backup-v2
roleRef:
  kind: Role
  name: {{ .Values.name }}-db-backup-v2
  apiGroup: rbac.authorization.k8s.io
{{- end }}