apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-{{.Values.name}}-etc
  labels:
    app: mariadb
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: database
data:
  mariadb.cnf: |
    [mysqld]
    max_connections           = 1024
    connect_timeout           = 30
    wait_timeout              = 3800
    innodb_buffer_pool_size   = {{ .Values.buffer_pool_size }}
    innodb_log_file_size      = {{ .Values.log_file_size }}
    innodb_open_files         = 4000
    innodb_stats_on_metadata  = 0
    innodb_thread_concurrency = 0
    innodb_read_io_threads    = 8
    innodb_write_io_threads   = 8
    innodb_print_all_deadlocks = 1
    query_cache_size          = 1M
    query_cache_type          = 1
    thread_cache_size         = 256
    join_buffer_size          = 4M
    innodb_checksum_algorithm = crc32
    sql_mode                  = "TRADITIONAL"
    slow_query_log            = 1
    long_query_time           = 3
{{- if .Values.backup_v2.enabled }}
    binlog_format             = {{ .Values.binlog_format }}
    expire_logs_days          = {{ .Values.expire_logs_days }}
    server-id                 = 1
    log_bin                   = mysqld-bin
    log_slow_admin_statements = OFF
{{- end }}
{{- if .Values.extraConfigFiles }}
{{ toYaml .Values.extraConfigFiles | indent 2 }}
{{- end }}
