apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-relay
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  {{- if .Values.relay.asHook }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "15"
  {{- end }}
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/relay: {{ .Values.config.relay | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-relay.yaml") . | sha256sum }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: relay
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-relay-init
          image: "{{ template "relay.image" . }}"
          imagePullPolicy: IfNotPresent
          args:
            - "credentials"
            - "generate"
          env:
            - name: RELAY_PORT
              value: '{{ template "relay.port" }}'
          volumeMounts:
            - name: credentials
              mountPath: /work/.relay
            - name: config
              mountPath: /work/.relay/config.yml
              subPath: config.yml
              readOnly: true
      containers:
      - name: {{ .Chart.Name }}-relay
        image: "{{ template "relay.image" . }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ template "relay.port" }}
        env:
        - name: RELAY_PORT
          value: '{{ template "relay.port" }}'
        volumeMounts:
          - name: credentials
            mountPath: /work/.relay
          - name: config
            mountPath: /work/.relay/config.yml
            subPath: config.yml
            readOnly: true
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/relay/healthcheck/ready/
            port: {{ template "relay.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.relay.probeInitialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/relay/healthcheck/ready/
            port: {{ template "relay.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.relay.probeInitialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-relay
          defaultMode: 0644
      - name: credentials
        emptyDir: {}
      {{- if .Values.relay.priorityClassName }}
      priorityClassName: "{{ .Values.relay.priorityClassName }}"
      {{- end }}
