{{ $values := .Values }}
{{ range $cluster_id, $config := .Values.limes.clusters }}
kind: Service
apiVersion: v1

metadata:
  name: limes-api-{{$cluster_id}}
  labels:
    app: limes-api
  annotations:
    # uncomment to have Maia scape as well: maia.io/scrape: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    # The `openstack` Prometheus shall scrape metrics of OpenStack services.
    prometheus.io/targets: {{ required ".Values.alerts.prometheus.openstack missing" $values.alerts.prometheus.openstack | quote }}

spec:
  selector:
    name: limes-api-{{$cluster_id}}
  ports:
    - port: 80

---
{{end}}
