{{ range $cluster_id, $config := .Values.limes.certs }}
kind: Ingress
{{- if $.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}

metadata:
  name: limes-api-{{$cluster_id}}
  labels:
    app: limes-api
  {{- if $config.vice_president }}
  annotations:
    vice-president: "true"
  {{- end }}

spec:
  tls:
    - secretName: limes-api-{{$cluster_id}}
      hosts: [ {{ $config.domain }} ]
  rules:
    - host: {{ $config.domain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: limes-api-{{$cluster_id}}
              servicePort: 80

---
{{end}}
