{{- if .Values.limes.clusters.ccloud -}}

apiVersion: "openstack.stable.sap.cc/v1"
kind: OpenstackSeed
metadata:
  name: limes-seed

spec:
  requires:
  - {{ default .Release.Namespace .Values.global.keystoneNamespace }}/keystone-seed
  - monsoon3/neutron-seed
#  - openstack/nova-seed  # uncomment once nova brings its own seed
#  - openstack/cinder-seed  # uncomment once cinder brings its own seed
  - monsoon3/manila-seed
  - monsoon3/barbican-seed
  - monsoon3/designate-seed
  - swift/swift-seed
  - monsoon3/domain-bs-seed
  - monsoon3/domain-cp-seed
  - monsoon3/domain-cc3test-seed
  - monsoon3/domain-ccadmin-seed
  - monsoon3/domain-default-seed
  - monsoon3/domain-fsn-seed
  - monsoon3/domain-hcm-seed
  - monsoon3/domain-hcp03-seed
  - monsoon3/domain-hec-seed
  - monsoon3/domain-monsoon3-seed
  - monsoon3/domain-neo-seed
  - monsoon3/domain-s4-seed
  - monsoon3/domain-wbs-seed

  roles:
    - name: cloud_resource_admin
    - name: cloud_resource_viewer
    - name: cloud_dns_resource_admin
    - name: resource_admin
    - name: resource_viewer
    - name: resource_service

  services:
    - name:        limes
      type:        resources
      description: 'Hierarchical quota/usage tracking'
      enabled:     true
      endpoints:
        - region:    '{{.Values.global.region}}'
          interface: public
          enabled:   true
          url:       '{{.Values.limes.clusters.ccloud.catalog_url}}'
        - region:    '{{.Values.global.region}}'
          interface: internal
          enabled:   true
          url:       'http://limes-api-ccloud.{{.Release.Namespace}}.svc'

  domains:
    - name: Default
      users:
        - name: limes
          description: Limes Service
          password: '{{.Values.limes.clusters.ccloud.auth.password}}'
          role_assignments:
            - project: service
              role:    service

    - name: ccadmin
      projects:
      - name: cloud_admin
        role_assignments:
          # permission to enumerate all projects and domains
          - user: limes@Default
            role: admin
          # (new-style) permission to manage all services' quotas
          - user: limes@Default
            role: resource_service
          # (old-style) permission to manage all services' quotas
          - user: limes@Default
            role: cloud_network_admin
          - user: limes@Default
            role: cloud_compute_admin
          - user: limes@Default
            role: cloud_volume_admin
          - user: limes@Default
            role: cloud_sharedfilesystem_admin
          - user: limes@Default
            role: cloud_keymanager_admin
          - user: limes@Default
            role: cloud_dns_admin
          - user: limes@Default
            role:  swiftreseller
          # permission to inspect metadata for private images (to determine OS type)
          - user: limes@Default
            role: cloud_image_admin
      groups:
      - name: CCADMIN_CLOUD_ADMINS
        role_assignments:
        - project: cloud_admin
          role: cloud_resource_admin
      - name: CCADMIN_DOMAIN_RESOURCE_ADMINS
        role_assignments:
        - domain: ccadmin
          role: resource_admin
      - name: CCADMIN_DOMAIN_DNS_OPS
        role_assignments:
        - domain: ccadmin
          role: cloud_dns_resource_admin
          inherited: true

    - name: bs
      groups:
      - name: BS_DOMAIN_RESOURCE_ADMINS
        role_assignments:
        - domain: bs
          role: resource_admin
      - name: BS_DOMAIN_DNS_OPS
        role_assignments:
        - domain: bs
          role: cloud_dns_resource_admin
          inherited: true

    - name: cc3test
      groups:
      - name: CC3TEST_DOMAIN_RESOURCE_ADMINS
        role_assignments:
        - domain: cc3test
          role: resource_admin
      - name: CC3TEST_DOMAIN_DNS_OPS
        role_assignments:
        - domain: cc3test
          role: cloud_dns_resource_admin
          inherited: true

    - name: cp
      groups:
      - name: CP_DOMAIN_RESOURCE_ADMINS
        role_assignments:
        - domain: cp
          role: resource_admin
      - name: CP_DOMAIN_DNS_OPS
        role_assignments:
        - domain: cp
          role: cloud_dns_resource_admin
          inherited: true

    - name: fsn
      groups:
      - name: FSN_DOMAIN_RESOURCE_ADMINS
        role_assignments:
        - domain: fsn
          role: resource_admin
      - name: FSN_DOMAIN_DNS_OPS
        role_assignments:
        - domain: fsn
          role: cloud_dns_resource_admin
          inherited: true

    - name: hcm
      groups:
      - name: HCM_DOMAIN_RESOURCE_ADMINS
        role_assignments:
        - domain: hcm
          role: resource_admin
      - name: HCM_DOMAIN_DNS_OPS
        role_assignments:
        - domain: hcm
          role: cloud_dns_resource_admin
          inherited: true

    - name: hcp03
      groups:
      - name: HCP03_DOMAIN_RESOURCE_ADMINS
        role_assignments:
        - domain: hcp03
          role: resource_admin
      - name: HCP03_DOMAIN_DNS_OPS
        role_assignments:
        - domain: hcp03
          role: cloud_dns_resource_admin
          inherited: true

    - name: hec
      groups:
      - name: HEC_DOMAIN_RESOURCE_ADMINS
        role_assignments:
        - domain: hec
          role: resource_admin
      - name: HEC_DOMAIN_DNS_OPS
        role_assignments:
        - domain: hec
          role: cloud_dns_resource_admin
          inherited: true

    - name: monsoon3
      groups:
      - name: MONSOON3_DOMAIN_RESOURCE_ADMINS
        role_assignments:
        - domain: monsoon3
          role: resource_admin
      - name: MONSOON3_DOMAIN_DNS_OPS
        role_assignments:
        - domain: monsoon3
          role: cloud_dns_resource_admin
          inherited: true

    - name: neo
      groups:
      - name: NEO_DOMAIN_RESOURCE_ADMINS
        role_assignments:
        - domain: neo
          role: resource_admin
      - name: NEO_DOMAIN_DNS_OPS
        role_assignments:
        - domain: neo
          role: cloud_dns_resource_admin
          inherited: true

    - name: s4
      groups:
      - name: S4_DOMAIN_RESOURCE_ADMINS
        role_assignments:
        - domain: s4
          role: resource_admin
      - name: S4_DOMAIN_DNS_OPS
        role_assignments:
        - domain: s4
          role: cloud_dns_resource_admin
          inherited: true

    - name: wbs
      groups:
      - name: WBS_DOMAIN_RESOURCE_ADMINS
        role_assignments:
        - domain: wbs
          role: resource_admin
      - name: WBS_DOMAIN_DNS_OPS
        role_assignments:
        - domain: wbs
          role: cloud_dns_resource_admin
          inherited: true

{{- end -}}
