{{- $values := .Values }}

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: network-interconnect-sre-aggregations
  labels:
    tier: sre
    type: aggregation-rules
    prometheus: {{ required ".Values.aggregations.prometheus missing" $values.aggregations.prometheus }}

spec:
  groups:
  - name: network-interconnect-sre.aggregations
    rules:
{{- range $period := $values.sre.periods }}
    - record: global:network_interconnect_availability_sli:ratio_rate{{$period}}
      expr: rate(cloudprober_success[{{$period}}])/rate(cloudprober_total[{{$period}}])
    - record: global:network_interconnect_latency_sli:milliseconds_rate{{$period}}
      expr: rate(cloudprober_latency_sum[{{$period}}])/rate(cloudprober_latency_count[{{$period}}])
{{- end }}