apiVersion: v1
kind: Secret

metadata:
  name: infra-global-additional-scrape-config
  labels:
    prometheus: infra-global

data:
  scrape-config.yaml: {{ include (print $.Template.BasePath  "/_prometheus.yaml.tpl") . | b64enc }}
