{{- range $suffix := list "" "-multipath" }}
---
kind: DaemonSet
apiVersion: extensions/v1beta1

metadata:
  name: swift-drive-autopilot{{$suffix}}
  labels:
    release: "{{$.Release.Name}}"

spec:
  minReadySeconds: 15
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: swift-drive-autopilot{{$suffix}}
        from: daemonset
        release: "{{$.Release.Name}}"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
    spec:
      tolerations:
      - key: "species"
        operator: "Equal"
        value: "{{$.Values.species}}"
        effect: "NoSchedule"
      {{- if eq $suffix "-multipath" }}
      - key: "species"
        operator: "Equal"
        value: "{{$.Values.species}}-multipath"
        effect: "NoSchedule"
      {{- end }}
      nodeSelector:
        species: {{quote $.Values.species}}
        {{- if eq $suffix "-multipath" }}
        multipath-disks: "true"
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: swift-drive-autopilot
        - name: coreos
          hostPath:
            path: /
      containers:
        - name: boot
          image: {{$.Values.global.imageRegistry}}/monsoon/swift-drive-autopilot:{{include "image_version" $}}
          securityContext:
            privileged: true
          args:
            - /etc/drive-autopilot/config{{$suffix}}.yaml
          # env:
          #   - name: 'DEBUG'
          #     value: '1'
          volumeMounts:
            - mountPath: /etc/drive-autopilot
              name: config
            - mountPath: /coreos
              name: coreos
          ports:
            - name: metrics
              containerPort: 9102
{{- end }}
