apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: records.disco.stable.sap.cc
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.record
    description: The record
    name: record
    type: string
  - JSONPath: .spec.type
    description: The type of the record
    name: type
    type: string
  group: disco.stable.sap.cc
  names:
    kind: Record
    listKind: RecordList
    plural: records
    singular: record
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata: {}
        spec:
          description: RecordSpec is the spec for a Record resource
          properties:
            description:
              description: Optional description for the record.
              type: string
            hosts:
              description: List of hostnames.
              items:
                type: string
              type: array
            record:
              description: The record to use.
              type: string
            type:
              description: Type of the DNS record. Currently supported are A, CNAME, SOA, NS records.
              type: string
            zoneName:
              description: Optional zone for the record.
              type: string
          required:
          - type
          - hosts
          - record
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
