# Default values for quay.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/coreos/quay
  tag: v2.9.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  # externalIP:


postgresql:
  image: sapcc/postgres
  imageTag: 9.5.10
  persistence:
    enabled: true
    size: 300Gi

  # Disable default Postgres alerts. Quay uses its own.
  alerts:
    enabled: false

#pullSecret:

# Default Prometheus alerts and rules.
alerts:
  enabled: true

  # Name of the Prometheus supposed to scrape the metrics and to which alerts are assigned.
  prometheus: kubernetes
