apiVersion: v1
kind: Service
metadata:
  name: octavia-api
  labels:
    app.kubernetes.io/name: octavia-api
    helm.sh/chart: {{ include "octavia.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    system: openstack
    type: api
    component: octavia
{{- if .Values.watcher.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{.Values.statsd.port | quote }}
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
{{- end }}
spec:
  ports:
    - port: {{.Values.api_port_internal}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: octavia-api
    app.kubernetes.io/instance: {{ .Release.Name }}