apiVersion: batch/v1
kind: Job
metadata:
  name: octavia-migration
  labels:
    system: openstack
    type: configuration
    component: octavia
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: octavia-migration
          image: {{required ".Values.global.imageRegistry is missing" .Values.global.imageRegistry}}/{{.Values.global.imageNamespace}}/loci-octavia:{{required "Values.imageVersion is missing" .Values.imageVersion}}
          imagePullPolicy: IfNotPresent
          command: ['dumb-init', 'kubernetes-entrypoint']
          env:
            - name: COMMAND
              value: "octavia-db-manage upgrade head"
            - name: DEPENDENCY_SERVICE
              value: "{{ .Release.Name }}-mariadb"
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            {{- if .Values.sentry.enabled }}
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry
                  key: octavia.DSN.python
            {{- end }}
          volumeMounts:
            - name: octavia-etc
              mountPath: /etc/octavia/octavia.conf
              subPath: octavia.conf
              readOnly: true
            - name: octavia-etc
              mountPath: /etc/octavia/logging.ini
              subPath: logging.ini
              readOnly: true
      volumes:
        - name: octavia-etc
          configMap:
            name: octavia-etc
