apiVersion: v1
kind: Service
metadata:
  name: octavia-api
  labels:
    app.kubernetes.io/name: octavia-api
    helm.sh/chart: {{ include "octavia.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    system: openstack
    type: api
    component: octavia
spec:
  ports:
    - port: {{.Values.api_port_internal}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: octavia-api
    app.kubernetes.io/instance: {{ .Release.Name }}