global:
  imageRegistry: DEFINED_IN_VALUES_FILE

encryption_key: DEFINED_IN_VALUES_FILE
image_version: DEFINED_IN_VALUES_FILE
species: swift-storage

# This setting means that after every 20 disks allocated on one node, one disk
# will be set aside as spare capacity. (See swift-drive-autopilot docs for
# details.)
one_spare_disk_every: 20
