dependencies:
- name: concourse
  version: "8.2.2"
  repository: "https://kubernetes-charts.storage.googleapis.com/"
- name: nginx-ingress
  version: 0.29.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  conditioj: gitResourceProxy.enabled
