apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tiller
  labels:
    app: helm
    name: tiller
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.role.type }}
  name: {{ .Values.role.name }}
subjects:
- kind: ServiceAccount
  name: tiller
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- else }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
