{{- if .Values.includeService }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller
  {{- if hasKey .Values "namespace" }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    app: helm
    name: tiller
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}