{{- if .Values.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ template "fullname" . }}-pgmetrics-alerts
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: metrics
    type: alerting-rules
    prometheus: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus }}

spec:
{{ include (print .Template.BasePath "/alerts/_database.alerts.tpl") . | indent 2 }}

{{- end }}
