apiVersion: v1
kind: ConfigMap
metadata:
  name: bin-backup-cleanup

data:
  sleep-for: |
{{ .Files.Get "bin/sleep-for" | indent 4 }}
  exponential-backoff: |
{{ .Files.Get "bin/exponential-backoff" | indent 4 }}
  cleanup: |
{{ .Files.Get "bin/cleanup" | indent 4 }}
