{{- $values := .Values }}
{{- if $values.alerts.enabled }}
{{- if $values.sidecars.parrot }}
{{- range $path, $bytes := .Files.Glob "alerts/*parrot.alerts" }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ printf "%s" $path | replace "/" "-" }}
  labels:
    app: kube-parrot
    tier: k8s
    type: alerting-rules
    prometheus: {{ required ".Values.alerts.prometheus missing" $values.alerts.prometheus }}

spec:
{{ printf "%s" $bytes | indent 2 }}

{{- end }}
{{- end }}
{{- end }}
