{{- if contains "baremetal" .Values.ml2_mechanismdrivers }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-ironic-agent
  labels:
    system: openstack
    type: configuration
    component: neutron

data:
  ironic_neutron_agent.ini: |
{{ include (print .Template.BasePath "/etc/_ironic_neutron_agent.ini.tpl") . | indent 4 }}
{{- end }}