{{- if contains ",f5" .Values.ml2_mechanismdrivers }}
{{- range $loadbalancer := .Values.new_f5.loadbalancers }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-f5-agent-{{$loadbalancer.name}}
  labels:
    system: openstack
    type: configuration
    component: neutron

data:
  f5-agent.conf.ini: |
{{ tuple $.Values $loadbalancer | include "f5_agent_conf_ini" | indent 4 }}

{{- end }}
{{- end }}
