kind: Service
apiVersion: v1
metadata:
  name: neutron-sftp-backup
  labels:
    release: "{{.Release.Name}}"
spec:
  selector:
    component: neutron-sftp-backup
  ports:
    - name: sftp
      port: 10022
      targetPort: 10022
  externalIPs:
{{ .Values.sftp.externalIPs | toYaml | indent 4 }}
