global:
  region: regionOne
  domain: evil.corp

additional_modules: |
  http_ca_myca:
    prober: http
    http:
      fail_if_not_ssl: true
      preferred_ip_protocol: ip4
      no_follow_redirects: false
      tls_config:
        ca_file: /etc/blackbox-exporter/myca.crt
