apiVersion: v1
kind: Service
metadata:
  name: es-manager
  namespace: hermes
  labels:
    system: openstack
    service: audit
    component: es-manager
    role: manager
spec:
  selector:
    component: es-manager
    role: manager
  ports:
    - name: manager
      port: {{.Values.hermes.elasticsearch.manager_port_internal}}
