apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: hermes
  labels:
    system: openstack
    service: audit
  annotations:
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "9198"
spec:
  selector:
    component: logstash
  ports:
    - port: 9198