kind: Service
apiVersion: v1
metadata:
  name: vrops-exporter 
  namespace: infra-monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.vrops.port_number | quote }}
    prometheus.io/targets: {{ required ".Values.vrops.alerts.prometheus missing" .Values.vrops.alerts.prometheus | quote }}
spec:
  selector:
    app: vrops-exporter
  ports:
    - name: metrics
      port: {{ .Values.vrops.port_number }}
