kind: Service
apiVersion: v1
metadata:
  name: vrops-exporter-vm 
  namespace: infra-monitoring
spec:
  selector:
    app: vrops-exporter-vm
  ports:
    - name: metrics
      port: {{ .Values.vrops.port_number }}
