kind: Service
apiVersion: v1
metadata:
  name: vrops-inventory
  namespace: infra-monitoring
spec:
  selector:
    app: vrops-inventory
  ports:
    - name: metrics
      port: {{ .Values.vrops.inventory_port_number }}
