{{- if required ".Values.global.netapp is missing" .Values.global.netapp }}
{{- if .Values.global.netapp.filers }}
{{- range $i, $share := .Values.global.netapp.filers -}}
{{ list $ $share | include "share_netapp_nanny" }}
---
{{- end -}}
{{- end -}}
{{- end -}}
