{{- if .Values.api.pdb.minAvailable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: keystone-api
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      name: keystone-api
      system: openstack
      component: keystone
      type: api
{{- end }}