global:
  region: regionOne
  domain: evil.corp

ingress:
  tls_client_auth:
    cacrt: |
      -----BEGIN CERTIFICATE-----
      superSecretCertificate
      -----END CERTIFICATE-----

vice-president:
  vice:
    cert: |
      -----BEGIN CERTIFICATE-----
      superSecretCertificate
      -----END CERTIFICATE-----
    key: |
      -----BEGIN PRIVATE KEY-----
      superSecretPrivateKey
      -----END PRIVATE KEY-----

    firstName: vice
    lastName: president
    email: vice@president.com
    country: DE
    province: Berlin
    locality: Berlin
    organization: Evil corp
    organizationalUnit: RD
    defaultChallenge: topSecret!

disco:
  enabled: true
  seed:
    enabled: true

  openstack:
    authURL:            https://keystone.staging.evil.corp:5000/v3
    regionName:         staging
    username:           user
    userDomainName:     Default
    password:           topSecret!
    projectName:        master
    projectDomainName:  Default
    zoneName:           staging.evil.corp.

  record: ingress.staging.evil.corp.

manila-provisioner:
  storageClass:
    zones: xy-xy-1a
    osShareNetworkID: xxxxxx-xxxx-xxxx-xxxx
    nfs-share-client: "0.0.0.0/0"
  openstack:
    authURL: https://keystone.staging.evil.corp:5000/v3
    userName: user
    password: password
    projectName: ""
    projectID: xyxyxyxy
    domainName: domain
    region: xy-xy-1
