kind: Service
apiVersion: v1

metadata:
  name: designate-api
  labels:
    system: openstack
    application: designate
    type: api
    component: api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ required ".Values.global.designate_metrics_port missing" .Values.global.designate_metrics_port | quote }}
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
spec:
  selector:
    app: designate-api
  ports:
    - name: designate-api
      port: {{.Values.global.designate_api_port_internal}}
