apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: disco-secret
  labels:
    app: disco

data:
  os-password: {{ required ".Values.openstack.password missing" .Values.openstack.password | b64enc | quote }}
