imageRegistry: hub.global.cloud.sap
imageRepository: monsoon/wham
imageTag: 191138cc
metricPort: 9090
listenPort: 80
debugLevel: "info"

os_user_domain_name: "Default"
os_project_name: "master"
os_project_domain_name: "ccadmin"
