apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager

data:
  alertmanager.yml: |
    global:
      resolve_timeout: 16m

    templates:
      - ./*.tmpl

    route:
      receiver: "nirvana"
      group_by: ['alertname']

    receivers:
    - name: "nirvana"
      webhook_configs:
      - url: 'https://nirvana:8080'
        send_resolved: false

  {{- $files := .Files }}
  {{ range tuple "slack.tmpl" "pagerduty.tmpl" }}
  {{ . }}: |
{{ $files.Get . | indent 4 }}
  {{- end }}
