apiVersion: v1
kind: Secret

metadata:
  name: os-global-additional-scrape-config
  labels:
    prometheus: os-global

data:
  scrape-config.yaml: {{ include (print $.Template.BasePath  "/_prometheus.yaml.tpl") . | b64enc }}
