enabled: false
image:
  repository: monsoon/ironic-exporter
  tag: 0d335501
port_number: 9191

log_level: "INFO"
os_user_domain_name: "Default"
os_project_name: "master"
os_project_domain_name: "ccadmin"

# Deploy Ironic Prometheus alerts.
alerts:
  # Name of the Prometheus to which the alerts should be assigned to.
  prometheus: openstack
