{{- if .Values.swift_account_caretaker.enable }}
kind: DaemonSet
apiVersion: extensions/v1beta1

metadata:
  name: swift-account-caretaker-collect
  labels:
    release: "{{.Release.Name}}"
    on-upgrade: recreate

spec:
  minReadySeconds: 15
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: swift-account-caretaker-collect
        from: daemonset
      annotations:
        checksum/caretaker.etc: {{ include "swift-utils/templates/caretaker-configmap.yaml" . | sha256sum }}
    spec:
      tolerations:
      - key: "species"
        operator: "Equal"
        value: "{{.Values.species}}"
        effect: "NoSchedule"
      - key: "species"
        operator: "Equal"
        value: "{{.Values.species}}-multipath"
        effect: "NoSchedule"
      # Run daemonset in Hostnetwork to get the real hostname
      hostNetwork: true
      nodeSelector:
        species: {{ .Values.species }}
      volumes:
        - name: caretaker-etc
          configMap:
            name: swift-account-caretaker
        - name: swift-drives
          hostPath:
            path: /srv/node
        - name: swift-drive-state
          hostPath:
            path: /run/swift-storage/state
      containers:
        - name: caretaker
          image: {{ include "swift_image" . }}
          command:
            - /usr/bin/dumb-init
          args:
            - /bin/bash
            - /usr/bin/swift-start
            - account-caretaker-collect
          # privileged access required for /swift-bin/unmount-helper (TODO: use shared/slave mount namespace instead)
          securityContext:
            privileged: true
          env:
            - name: DEBUG_CONTAINER
              value: "false"
          volumeMounts:
            - mountPath: /caretaker-etc
              name: caretaker-etc
            - mountPath: /srv/node
              name: swift-drives
            - mountPath: /swift-drive-state
              name: swift-drive-state
{{- end }}
