image:
  repository: hub.global.cloud.sap/monsoon/ccauth
  version: bdf899045c806060c5aaf0bc457fe40b4b9dd6b0
  
keystone:
  # host: calculated if not provided 
  adminUsername: admin
  # adminPassword: # from secrets
  adminDomain: Default
  adminProject: admin

ldap:
  # host: # calculated if not provided 
  # bindPW: # from secrets
  bindDN: CN=monsoon-service,CN=Users,DC=ad,DC=global,DC=cloud,DC=sap
  baseDN: OU=Identities,DC=ad,DC=global,DC=cloud,DC=sap

# global:
   # region: ap-au-1