kind: Service
apiVersion: v1

metadata:
  name: castellum-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}

spec:
  selector:
    name: castellum-api
  ports:
    - port: 8080
