kind: Ingress
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}

metadata:
  name: castellum-api
  annotations:
    vice-president: "true"
    disco: "true"

spec:
  tls:
    - secretName: castellum-api
      hosts: [ castellum.{{ .Values.global.region }}.{{ .Values.global.tld }} ]
  rules:
    - host: castellum.{{ .Values.global.region }}.{{ .Values.global.tld }}
      http:
        paths:
          - path: /
            backend:
              serviceName: castellum-api
              servicePort: 8080
