kind: Service
apiVersion: v1

metadata:
  name: keppel-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/targets: "openstack"

spec:
  selector:
    name: keppel-api
  ports:
    - port: 80
