kubernikus:
  imageTag: 0e6dd344c35881b9073dabfafbd7f898f9028336

  #use a dedicated serviceaccount and proper RBAC rules for this deployment
  standalone: false 
  useServiceAccount: true
  includeRBAC: true
  k8sniff:
    useRBAC: true

  api:
    policyFile: /etc/kubernikus/policy-ccadmin.json
  operator:
    nodeAffinity: false
    controllers: [groundctl, deorbiter, migration, servicing, certs]
  ingress:
    annotations:
      disco: "true"
kubernikus-dex:
  namespaceOverride: kubernikus
