apiVersion: v1
kind: Secret
metadata:
  name: {{ template "quay.fullname" . }}-pull-secret
data:
  .dockercfg: {{ required ".Values.pulllSecret is missing" .Values.pullSecret }}
type: kubernetes.io/dockercfg
