kind: Service
apiVersion: v1

metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
  name: elektra

spec:
  selector:
    name: elektra
  ports:
    - port: 80
