apiVersion: v1
kind: Service
metadata:
  name: {{ include "image-usage-exporter.fullname" . }}
  namespace: infra-monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.listen_port }}"
    prometheus.io/targets: "{{ .Values.alerts.prometheus }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "image-usage-exporter.selectorLabels" . | nindent 4 }}
