apiVersion: v1
kind: Service
metadata:
  labels:
    app: concourse-web
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
  name: concourse-web-lb
spec:
  ports:
  - name: tsa
    port: 2222
    protocol: TCP
    targetPort: tsa
  selector:
    app: concourse-web
  type: LoadBalancer
