# Default values for supernova.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replica_count: 2

image:
  repository: sapcc/supernova
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  internet_facing: false
#   enabled: false
#   probe: true
