dependencies:
  - name: postgresql
    repository: file://../../common/postgresql
    version: 0.3.0
  - name: pgmetrics
    repository: file://../../common/pgmetrics
    version: 0.1.0
  - name: redis
    repository: file://../../common/redis
    version: 1.0.1
