apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
{{- if .Values.metrics.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.port }}"
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: mosquitto
{{- if .Values.service.externalIPs }}
  externalIPs:
{{- range $ip := .Values.service.externalIPs }}
  - {{ $ip | quote }}
{{- end }}
{{ end }}
