kind: Service
apiVersion: v1

metadata:
  name: ironic-api
  labels:
    system: openstack
    type: api
    component: ironic
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{.Values.statsd.port | quote }}
    prometheus.io/targets: {{ required ".Values.alerts.prometheus missing" .Values.alerts.prometheus | quote }}

spec:
  selector:
    name: ironic-api
  ports:
    - name: ironic-api
      port: {{.Values.global.ironicApiPortInternal}}
      targetPort: ironic-api
