{{- if .Values.sentry.enabled }}
apiVersion: "sentry.sap.cc/v1"
kind: "SentryProject"
metadata:
  name: swift-sentry

spec:
  name: swift # slug of the project you want to use
  team: openstack # slug of the team where the project should be created (if it doesn't exist)
{{- end }}
